#!/usr/bin/env bash
# Factory Flow — first-time setup script
# Generates secrets, prompts for required values, and writes .env
# Works on Windows (Git Bash), macOS, and Linux

set -e

ENV_FILE=".env"

if [ -f "$ENV_FILE" ]; then
  echo ".env already exists. Delete it first if you want to re-run setup."
  exit 1
fi

echo ""
echo "Factory Flow — Setup"
echo "--------------------"
echo ""

# Prompt for Postgres password
while true; do
  read -rsp "Enter a database password (POSTGRES_PASSWORD): " POSTGRES_PASSWORD
  echo ""
  read -rsp "Confirm password: " POSTGRES_PASSWORD_CONFIRM
  echo ""
  if [ "$POSTGRES_PASSWORD" = "$POSTGRES_PASSWORD_CONFIRM" ]; then
    break
  fi
  echo "Passwords do not match. Try again."
done

# Prompt for APP_URL
echo ""
read -rp "Enter the app URL (e.g. http://localhost:5000 or https://your-domain.com): " APP_URL
APP_URL="${APP_URL:-http://localhost:5000}"

# Prompt for optional Postmark key
echo ""
read -rp "Postmark API key for emails (leave blank to disable): " POSTMARK_API_KEY

# Generate SESSION_SECRET using openssl (available in Git Bash, macOS, Linux)
SESSION_SECRET=$(openssl rand -hex 32)

cat > "$ENV_FILE" <<EOF
# Generated by setup.sh on $(date)

POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
SESSION_SECRET=${SESSION_SECRET}
APP_URL=${APP_URL}
POSTMARK_API_KEY=${POSTMARK_API_KEY}
EOF

echo ""
echo ".env written successfully."
echo ""
echo "Next step:"
echo "  docker compose up -d"
echo ""
echo "Or, if deploying from the pre-built image:"
echo "  docker compose -f docker-compose.release.yml up -d"
echo ""
